const fs = require('node:fs');
const path = require('node:path');

const root = process.cwd();
const appConfigPath = path.join(root, 'src', 'renderer', 'app', 'config.ts');
const registryPath = path.join(root, 'src', 'renderer', 'app', 'featureRegistry.ts');
const featuresDir = path.join(root, 'src', 'renderer', 'features');

function toKebabCase(input) {
  return input
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

function toPascalCase(input) {
  return input
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');
}

function escapeSingleQuote(input) {
  return input.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function insertBeforeToken(source, token, content) {
  const index = source.indexOf(token);
  if (index < 0) {
    throw new Error(`Token not found: ${token}`);
  }
  return `${source.slice(0, index)}${content}${source.slice(index)}`;
}

function main() {
  const rawName = process.argv[2];
  const rawLabel = process.argv[3] || rawName;

  if (!rawName) {
    throw new Error('Usage: npm run scaffold:feature -- <feature-name> [TabLabel]');
  }

  if (!fs.existsSync(appConfigPath) || !fs.existsSync(registryPath)) {
    throw new Error('Required app config files are missing.');
  }

  const featureId = toKebabCase(rawName);
  if (!featureId) {
    throw new Error('Invalid feature name.');
  }

  const pageName = `${toPascalCase(featureId)}Page`;
  const featureDir = path.join(featuresDir, featureId);
  const featureFile = path.join(featureDir, `${pageName}.tsx`);

  if (fs.existsSync(featureFile)) {
    throw new Error(`Feature already exists: ${featureFile}`);
  }

  fs.mkdirSync(featureDir, { recursive: true });
  fs.writeFileSync(
    featureFile,
    `function ${pageName}() {\n  return (\n    <section className=\"panel tool-panel\">\n      <header className=\"panel-head\">\n        <h1 className=\"title\">${escapeSingleQuote(rawLabel)}</h1>\n        <p className=\"subtitle\">Feature scaffold generated by template script.</p>\n      </header>\n      <div className=\"placeholder-box\">Implement your ${escapeSingleQuote(rawLabel)} feature here.</div>\n    </section>\n  );\n}\n\nexport default ${pageName};\n`,
    'utf8'
  );

  let appConfig = fs.readFileSync(appConfigPath, 'utf8');
  if (!appConfig.includes(`'${featureId}'`)) {
    appConfig = appConfig.replace(
      /export type AppTabId = ([^;]+);/,
      (_m, union) => `export type AppTabId = ${union} | '${featureId}';`
    );

    const tabLine = `  { id: '${featureId}', label: '${escapeSingleQuote(rawLabel)}', order: 100 },\n`;
    appConfig = insertBeforeToken(appConfig, '];', tabLine);
    fs.writeFileSync(appConfigPath, appConfig, 'utf8');
  }

  let registry = fs.readFileSync(registryPath, 'utf8');
  const importLine = `import ${pageName} from '../features/${featureId}/${pageName}';\n`;
  const featureComponentLine = `  { id: '${featureId}', component: ${pageName} },\n`;

  if (!registry.includes(importLine.trim())) {
    registry = insertBeforeToken(registry, '\ninterface FeatureManifestItem', `\n${importLine}`);
  }

  if (!registry.includes(featureComponentLine.trim())) {
    registry = insertBeforeToken(registry, '];', featureComponentLine);
  }

  fs.writeFileSync(registryPath, registry, 'utf8');

  console.log('[scaffold] feature created successfully:');
  console.log(`  - id: ${featureId}`);
  console.log(`  - tab label: ${rawLabel}`);
  console.log(`  - page: src/renderer/features/${featureId}/${pageName}.tsx`);
}

main();
